apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
  patch: |-
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: any
   spec:
     template:
       spec:
         containers:
         - name: app
           env:
           - name: FOO
             value: bar
